### ISSUE TITLE
.NET Core 3.0 & 3.1 - cannot resolve parameter IMemoryCache cache

### ISSUE THREAD

**Issue by slagbat** [stefanprodan/AspNetCoreRateLimit#106]
Since switching to .NET Core 3.0 and 3.1 I've been getting the following error with AspNetCoreRateLimit when the application/API starts up:

> 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'AspNetCoreRateLimit.MemoryCacheRateLimitCounterStore' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Caching.Memory.IMemoryCache cache' of constructor 'Void .ctor(Microsoft.Extensions.Caching.Memory.IMemoryCache)'.

I understand the error is saying it can't resolve the dependency IMemoryCache and by adding the following to the startup I'm able to get rid of it:

    services.AddSingleton<IMemoryCache, MemoryCache>()

But what concerns me is this didn't happen in earlier versions of .NET Core, it's not in any of the AspNetCoreRateLimit docs and I don't really know understand the implications of simply adding injecting the MemoryCache are!

Can anyone help me figure out what I'm missing/am doing wrong?

**Comment by MJMMN** [comment]
According to the microsoft documentation found here (https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1), registration of the IMemoryCache is a a byproduct of using other registration types.  (Mvc, ControllersWithViews, MvcCore, etc.).  It may be possible that some other change that was made removed a byproduct registration of IMemoryCache?

From the linked article:
> For most apps, IMemoryCache is enabled. For example, calling AddMvc, AddControllersWithViews, AddRazorPages, AddMvcCore().AddRazorViewEngine, and many other Add{Service} methods in ConfigureServices, enables IMemoryCache. For apps that are not calling one of the preceding Add{Service} methods, it may be necessary to call AddMemoryCache in ConfigureServices.
