### ISSUE TITLE
ClientRateLimiter throws error if header empty

### ISSUE THREAD

**Issue by andrasg** [stefanprodan/AspNetCoreRateLimit#11]
I have set up the client rate limiter to extract the user's identity from a http header. If the header is present but it's value is an empty string, the SetIdentity method will break on [line 99](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Middleware/ClientRateLimitMiddleware.cs#L99):

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AspNetCoreRateLimit.ClientRateLimitMiddleware.SetIdentity(HttpContext httpContext)
   at AspNetCoreRateLimit.ClientRateLimitMiddleware.<Invoke>d__5.MoveNext()
```

**Comment by stefanprodan** [comment]
This is the intended behavior, you can make your own ClientRateLimiter and override the SetIdentity method and implement your own logic when the header is empty.

**Comment by andrasg** [comment]
@stefanprodan, makes sense. Implemented it and overridden SetIdentity(). Works like a charm!
