### ISSUE TITLE
Is there a "monitor" mode?

### ISSUE THREAD

**Issue by arisliang** [stefanprodan/AspNetCoreRateLimit#112]
so it logs the overuse, instead of blocking calls?

My case is we want to log the API calls above the limit, perhaps to log it somewhere, but we still want to allow the calls to proceed. Is this possible now? If so, how should we do it?

**Comment by mexner** [comment]
+1 - also good for relaying stats on consumption usage to customers in a SaaS

**Comment by mikeerrecart** [comment]
Any news on that ?
I'd like to use such a feature (logging throttled request instead of blocking them).

Mike from France

**Comment by g4mb10r** [comment]
@arisliang @mexner @mikeerrecart 

This may not be exactly what you are looking for but if you are using Application Insights you can have it listen for the ILogger Information messages from the rate-limiting middleware. This can be done through appsettings.json.

e.g.

"Logging": {
"LogLevel": {
"Default": "Information",
"Microsoft": "Warning",
"Microsoft.Hosting.Lifetime": "Information"
},
"ApplicationInsights": {
"LogLevel": {
"Default": "Warning",
"AspNetCoreRateLimit": "Information"
}
}
}

In this example, we are telling Application Insights to record Warning (and above), except for when it comes to AspNetCoreRateLimit where we record Information (and above).

This lets you see the failure in Application Insights with a trace explaining why the request was blocked. I.e. what rule was applied.
