### ISSUE TITLE
Is there a way to read the settings from a different object other than the appsettings?

### ISSUE THREAD

**Issue by abbassep3200** [stefanprodan/AspNetCoreRateLimit#116]
Hi.
I our scenario, we get application configurations from a different object (not in appsettings).
Is there a way to read the settings from a different object other than the appsettings?
for example:
I don't want:
services.Configure<ClientRateLimitOptions>(Configuration.GetSection("ClientRateLimiting"));

I want:
services.Configure<ClientRateLimitOptions>(anyObject));

**Comment by bendoyon** [comment]
@abbassep3200 Yes, you can use appsettings, environment variables, command line arguments, in-memory collections or any configuration provider you wish.

This is a .NET Core question, not an issue for this library. I would recommend closing this issue.

You can check https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1 for more information about how to setup configuration sources.

**Comment by harigator** [comment]
For anyone seeking a reference on how the environment variables should be defined for .net core 5.0 running on containers:

### variables in .env file:
```
ClientRateLimiting__ClientIdHeader=authorization
ClientRateLimiting__EnableEndpointRateLimiting=true
ClientRateLimiting__GeneralRules__0__Endpoint=get:/applicant/*/pdf
ClientRateLimiting__GeneralRules__0__Limit=2
ClientRateLimiting__GeneralRules__0__Period=30s
ClientRateLimiting__HttpStatusCode=429
ClientRateLimiting__StackBlockedRequests=false
```

### env variables in json file:
```
"ClientRateLimiting__ClientIdHeader": "authorization",
"ClientRateLimiting__EnableEndpointRateLimiting": "true",
"ClientRateLimiting__GeneralRules__0__Endpoint": "get:/applicant/submission/*/pdf",
"ClientRateLimiting__GeneralRules__0__Limit": "2",
"ClientRateLimiting__GeneralRules__0__Period": "30s",
"ClientRateLimiting__HttpStatusCode": "429",
"ClientRateLimiting__StackBlockedRequests": "false",
```

### Yaml file (example: AWS cloudformation definition):
```
- Name: ClientRateLimiting__EnableEndpointRateLimiting
  Value: true
- Name: ClientRateLimiting__StackBlockedRequests
  Value: false
- Name: ClientRateLimiting__ClientIdHeader
  Value: authorization
- Name: ClientRateLimiting__HttpStatusCode
  Value: 429
- Name: ClientRateLimiting__GeneralRules__0__Endpoint
  Value: get:/applicant/submission/*/pdf
- Name: ClientRateLimiting__GeneralRules__0__Period
  Value: 20s
- Name: ClientRateLimiting__GeneralRules__0__Limit
  Value: 5
```
