### ISSUE TITLE
Why is the decrement 2 ？

### ISSUE THREAD

**Issue by EminemJK** [stefanprodan/AspNetCoreRateLimit#119]
> {
  "IpRateLimiting": {
    "EnableEndpointRateLimiting": true,
    "StackBlockedRequests": false,
    "RealIpHeader": "X-Real-IP",
    "ClientIdHeader": "X-ClientId",
    "HttpStatusCode": 200,
    "QuotaExceededResponse": {
      "Content": "{{\"code\":429,\"msg\":\"访问过于频繁，请稍后重试\",\"data\":null}}",
      "ContentType": "application/json",
      "StatusCode": 200
    },
    "IpWhitelist": [ "127.0.0.1", "::1" ],
    "EndpointWhitelist": [],
    "ClientWhitelist": [],
    "GeneralRules": [
      {
        "Endpoint": "*:/api/Account/SkillSubsidies/GetDetail",
        "Period": "1m",
        "Limit": 20
      }
    ]
  }
}

Fiddler Test：
![1](https://user-images.githubusercontent.com/33885904/79185417-62970c00-7e49-11ea-84c5-8f6eb856a7dd.png)
![2](https://user-images.githubusercontent.com/33885904/79185419-63c83900-7e49-11ea-9b31-49f23f0768d8.png)
![3](https://user-images.githubusercontent.com/33885904/79185423-6460cf80-7e49-11ea-8a26-4312e181b50d.png)
![4](https://user-images.githubusercontent.com/33885904/79185461-80647100-7e49-11ea-99ab-eef1987babfd.png)

**Comment by EminemJK** [comment]
Base:
.Net Code 2.2  WebApi
Fiddel v5.0

**Comment by EminemJK** [comment]
Oh，I see what the problem is this
`
   public class IPLimitMiddleware : IpRateLimitMiddleware
    {
        public IPLimitMiddleware(RequestDelegate next, IOptions<IpRateLimitOptions> options, IRateLimitCounterStore counterStore, IIpPolicyStore policyStore, IRateLimitConfiguration config, ILogger<IpRateLimitMiddleware> logger)
            : base(next, options, counterStore, policyStore, config, logger)
        {
        }

        public override Task ReturnQuotaExceededResponse(HttpContext httpContext, RateLimitRule rule, string retryAfter)
        {
            httpContext.Response.Headers.Append("Access-Control-Allow-Origin", "*");
            return base.ReturnQuotaExceededResponse(httpContext, rule, retryAfter);
        }
    }

 app.UseMiddleware<IPLimitMiddleware>().UseIpRateLimiting();
`

**Comment by EminemJK** [comment]
The solution：app.UseMiddleware<IPLimitMiddleware>()；

**Comment by cristipufu** [comment]
To clarify this: you were applying the same middleware twice:
- `app.UseMiddleware<IPLimitMiddleware>()`
- `app.UseIpRateLimiting()`

**Comment by EminemJK** [comment]
> To clarify this: you were applying the same middleware twice:
> 
> * `app.UseMiddleware<IPLimitMiddleware>()`
> * `app.UseIpRateLimiting()`

yes，I was so confused，thank you.
