### ISSUE TITLE
Does rate limiter respects cors? 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [stefanprodan/AspNetCoreRateLimit#120]
I.e. proper CORS headers will be returned in case of rate limiting? Or where in pipe line I have to put rate limiter vs CORS?

**Comment by bendoyon** [comment]
@dzmitry-lahoda That depends on the configuration in your .NET Core Startup class. The order in which you setup your middleware will determine if whatever is handling your CORS header will go first or not.

You can check for more information here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1

I would recommend closing this issue, as it's not related to this library at all.

**Comment by dzmitry-lahoda** [comment]
We have 
```
            app.UseIpRateLimiting();
            app.UseCors();
```

and we see
 
![image](https://user-images.githubusercontent.com/757125/79631556-be6fd680-8162-11ea-9ade-0c3d25c18bd4.png)

from time to time, especially when was hit by #121 

so having next may help? CORS will add headers and we will see 429 error in browser instead of CORS? or if not, CORS issues should be raised?
```
            app.UseCors();
            app.UseIpRateLimiting();
```
