### ISSUE TITLE
Daily Rate Limit Not Being Hit

### ISSUE THREAD

**Issue by burgoyne** [stefanprodan/AspNetCoreRateLimit#124]
I have the rate limiting set to only allow 3000 calls per day. I just ran a test through Postman of 4000 calls to the same endpoint, and they all went through and returned a 200 (running my API on localhost). 

Any suggestions for what I am doing wrong? 

```
"IpRateLimiting": {
    "EnableEndpointRateLimiting": false,
    "StackBlockedRequests": false,
    "RealIpHeader": "X-Real-IP",
    "ClientIdHeader": "X-ClientId",
    "HttpStatusCode": 429,
    "QuotaExceededMessage": "You have reached your call limit! Only 1 call is permitted per second, or 3000 per day.",
    "GeneralRules": [
      {
        "Endpoint": "*",
        "Period": "1s",
        "Limit": 1
      },
      {
        "Endpoint": "*",
        "Period": "24h",
        "Limit": 3000
      }
    ]
  }
```

Startup ConfigureServices:
```
services.AddOptions();
            services.AddMemoryCache();
            services.Configure<IpRateLimitOptions>(Configuration.GetSection("IpRateLimiting"));
            services.Configure<IpRateLimitPolicies>(Configuration.GetSection("IpRateLimitPolicies"));
            services.AddSingleton<IIpPolicyStore, MemoryCacheIpPolicyStore>();
            services.AddSingleton<IRateLimitCounterStore, MemoryCacheRateLimitCounterStore>();
            services.AddMvc();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<IRateLimitConfiguration, RateLimitConfiguration>();
```

Startup Configure:
`app.UseIpRateLimiting();`

**Comment by TheNillesen** [comment]
it might sound stupid, but since i dont experience any errors.. Did you try to change the rule from 24h to 1d? 
I have rules for 1s 15m 1h 1d and i hit them all, am however using ClientRateLimiting and not IpLimiting.

**Comment by burgoyne** [comment]
I just changed it to 1d and it still never hits the limit. My 1s rule is also never hit. 

What do you all use to test your endpoints? I am using Postman Runner, and I set it on my endpoint to run with 3005 iterations, and 1 ms delay. When finished, it says 0 passed 0 failed (I assume that's because I don't have any tests running?).

**Comment by burgoyne** [comment]
Ok, so I solved my own issue here. I decided to go through my `Startup.cs` file and put all of the requirements for the rate limiting at the top of my `ConfigureServices` method. That solved it. I never knew it mattered which order those are in.
