### ISSUE TITLE
Implement rule as key

### ISSUE THREAD

**Issue by flgarrid** [stefanprodan/AspNetCoreRateLimit#13]
Please, consider implementing this:
https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Core/RateLimitCore.cs#L33

Currently we have an endpoint that has a parameter like /api/values/1, /api/values/2, etc. and we need to restrict it as a whole.

Thanks!

**Comment by cristipufu** [comment]
Check this out https://github.com/stefanprodan/AspNetCoreRateLimit/pull/63
