### ISSUE TITLE
Is the latest version 3.0.5? I installed 3.0.5 through nuget

### ISSUE THREAD

**Issue by zhaoyanwenqi** [stefanprodan/AspNetCoreRateLimit#132]
Is the latest version 3.0.5? I installed 3.0.5 through nuget

But officially it's 3.0.3

Is the storage of different versions the same?

In version 3.0.5, what do I think about the hash table stored in redis.

How do I store string key value pairs in the source code?

Thank you for your advice

 public Task SetAsync(string id, T entry, TimeSpan? expirationTime = null, CancellationToken cancellationToken = default)
        {
            var options = new DistributedCacheEntryOptions();

            if (expirationTime.HasValue)
            {
                options.SetAbsoluteExpiration(expirationTime.Value);
            }

            return _cache.SetStringAsync(id, JsonConvert.SerializeObject(entry), options, cancellationToken);
        }

**Comment by cristipufu** [comment]
https://github.com/stefanprodan/AspNetCoreRateLimit/releases/tag/3.2.0

Duplicate: https://github.com/stefanprodan/AspNetCoreRateLimit/issues/133
