### ISSUE TITLE
[Question] How to ignore the gateway

### ISSUE THREAD

**Issue by LeonardoFaggiani** [stefanprodan/AspNetCoreRateLimit#134]
Hello, I have implemented aspNetRateLimit with distributed cache because we have the server with load balancer and an api gateway, I was seeing that at the moment of blocking it is blocking the gateway that we have.
                             
For example -> Client IP 200.00.00.00 ---> Gateway IP 10.0.0.0

The IP that is limited / blocked is that of the Gateway, not that of the Client, as I could do so that this does not happen and that the client's is blocked.

I made the test to consume 2 equal methods from different IPs and the first one that reaches the quota blocks the second, which in my scenario should not happen.

I hope the doubt is understood.
Thank you very much!

**Comment by cristipufu** [comment]
Usually, gateways send the real IP in a HTTP header. If you find out its name, you can configure it:
```js
"IpRateLimiting": {
    "EnableEndpointRateLimiting": false,
    "StackBlockedRequests": false,
    "RealIpHeader": "X-Real-IP",
}
```

**Comment by LeonardoFaggiani** [comment]
> Usually, gateways send the real IP in a HTTP header. If you find out its name, you can configure it:
> 
> ```js
> "IpRateLimiting": {
>     "EnableEndpointRateLimiting": false,
>     "StackBlockedRequests": false,
>     "RealIpHeader": "X-Real-IP",
> }
> ```

ok, I was reviewing the headers and I can't find one called X-Real-IP, if I found x-forwarded-for, which returns the IP of the client, but apparently it is not working, they are still blocked by the IP of the gateway.

this is my config:

   "IpRateLimit": {
     "EnableEndpointRateLimiting": true,
     "StackBlockedRequests": false,
     "RealIPHeader": "x-forwarded-for",
     "ClientIdHeader": "X-ClientId",
     "HttpStatusCode": 429,
     "GeneralRules": [
       {
         "Endpoint": "*: / api / *",
         "Period": "1m",
         "Limit": 10
       }
     ]
   },

**Comment by cristipufu** [comment]
You can try to implement and inject your own [IpHeaderResolveContributor](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Resolvers/IpHeaderResolveContributor.cs) - this way maybe you can debug why it doesn't properly read the IP header:
https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/Resolve-Contributors

**Comment by LeonardoFaggiani** [comment]
> You can try to implement and inject your own [IpHeaderResolveContributor](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Resolvers/IpHeaderResolveContributor.cs) - this way maybe you can debug why it doesn't properly read the IP header:
> https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/Resolve-Contributors

I did it, still keep taking the IP of api gateway.

My implementation:

IpRateLimitOptions? .RealIpHeader -> contains "x-forwered-for" but it doesn't work, so I hardcode it.

    public class CustomRateLimitConfiguration : RateLimitConfiguration
    {

        public CustomRateLimitConfiguration(IHttpContextAccessor httpContextAccessor, IOptions<IpRateLimitOptions> ipOptions, IOptions<ClientRateLimitOptions> clientOptions) : base(httpContextAccessor, ipOptions, clientOptions)
        {
        }

        protected override void RegisterResolvers()
        {
            base.RegisterResolvers();


            if (!string.IsNullOrEmpty(IpRateLimitOptions?.RealIpHeader))
            {
                IpResolvers.Add(new IpHeaderResolveContributor(HttpContextAccessor, "x-forwarded-for"));
            }
        }
    }`

I will debug it to see if I can find the bug

Thank you very much

**Comment by LeonardoFaggiani** [comment]
OK, after a long time, I found where the problem is generated, but could not find the cause that generates it :(
In the **_RateLimitMiddleware_** class the **_ResolveIdentity_** method 

https://github.com/stefanprodan/AspNetCoreRateLimit/blob/52b1fe0e5cbb3709f39b80c49e35fed89121c3a4/src/AspNetCoreRateLimit/Middleware/RateLimitMiddleware.cs#L131

In the RateLimitMiddleware class the ResolveIdentity method receives the httpContext, in the IpHeaderResolveContributor class in the ResolveIp method it retrieves the httpCotext from IHttpContextAccessor

For some reason I don't know the Header "x-forwarded-for" doesn't exist and returns string.empty, but in the context of the RateLimitMiddleware class if the header exists.

I have IHttpContextAccessor instantiated as singleton.

I fixed it by creating a private method in RateLimitMiddleware that receives the HttpContext per parameter and does the same as IpHeaderResolveContributor

Example:

        public virtual ClientRequestIdentity ResolveIdentity(HttpContext httpContext)
        {
            string clientIp = null;
            string clientId = null;

            if (_config.ClientResolvers?.Any() == true)
            {
                foreach (var resolver in _config.ClientResolvers)
                {
                    clientId = resolver.ResolveClient();

                    if (!string.IsNullOrEmpty(clientId))
                    {
                        break;
                    }
                }
            }

            if (_config.IpResolvers?.Any() == true)
            {
                foreach (var resolver in _config.IpResolvers)
                {
                    var dicIP = new Dictionary<string, string>();
                    
                    dicIP.Add(Guid.NewGuid().ToString(),$"IP {httpContext.Request.Headers["x-forwarded-for"]}");
                    _telemetryClient.TrackEvent("AntesResolveIP", dicIP);

                    clientIp = resolver.ResolveIp();
                    clientIp = ResolveIp(httpContext);

                    dicIP.Clear();
                    dicIP.Add(Guid.NewGuid().ToString(), $"IP:{ clientIp}");
                    _telemetryClient.TrackEvent("DespuesResolveIP", dicIP);

                    if (!string.IsNullOrEmpty(clientIp))
                    {
                        break;
                    }
                }
            }

            return new ClientRequestIdentity
            {
                ClientIp = clientIp,
                Path = httpContext.Request.Path.ToString().ToLowerInvariant(),
                HttpVerb = httpContext.Request.Method.ToLowerInvariant(),
                ClientId = clientId
            };
        }``

        private string ResolveIp(HttpContext httpContext)
        {
            IPAddress clientIp = null;
            
            if (httpContext.Request.Headers.TryGetValue("x-forwarded-for", out var values))
            {
                var dicIP = new Dictionary<string, string>();
                dicIP.Add(Guid.NewGuid().ToString(), $"Dentro del TryGetValue IP: {httpContext.Request.Headers["x-forwarded-for"]}");
                _telemetryClient.TrackEvent("AntesResolveIP", dicIP);
                clientIp = IpAddressUtil.ParseIp(values.Last());
            }

            return clientIp?.ToString();
        }


Doing the local tests the error does not happen, only when the api gateway is in the middle.

To find the problem I had to put logs of application insight.

Any idea what is causing the error?

Thanks in advance.

**Comment by cristipufu** [comment]
Should be fixed by https://github.com/stefanprodan/AspNetCoreRateLimit/commit/c35446c951978c796657aafe029f3961a730b45e

Please re-open if that's not the case.
