### ISSUE TITLE
Update the wiki on stefanprodan/AspNetCoreRateLimit

### ISSUE THREAD

**Issue by AprilHickson** [stefanprodan/AspNetCoreRateLimit#136]
I have made some changes to the wiki on these 2 pages:

https://github.com/AprilHickson/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware

https://github.com/AprilHickson/AspNetCoreRateLimit/wiki/ClientRateLimitMiddleware

These involve the new regex features in the pull request:

https://github.com/stefanprodan/AspNetCoreRateLimit/pull/135

**Comment by cristipufu** [comment]
I will publish the new NuGet package version soon and then update the wiki accordingly

**Comment by AprilHickson** [comment]
My bad, thanks!

**Comment by AprilHickson** [comment]
Hey is there an ETA on this? I have a project on hold, that I would love to carry on with.

**Comment by cristipufu** [comment]
Thank you for your patience: https://www.nuget.org/packages/AspNetCoreRateLimit/3.2.0
