### ISSUE TITLE
Rate limit rules based on whether or not a request is to an endpoint that needs authentication

### ISSUE THREAD

**Issue by dupuis2387** [stefanprodan/AspNetCoreRateLimit#145]
Hello,

I was wondering if I could get some help with/pointers for implementing rate limiting based on whether or not a request is hitting an api endpoint that needs authentication? 

I thought I could add a `GeneralRules` section to my `appsettings.json` file, where I start off with with the first rule targeting * and then get more specific, and override it, but it doesnt seem to work :

                    {
				"Endpoint": "*",
				"Period": "1h",
				"Limit": 60
			},
			{
				"Endpoint": "*:/my-non-authenticated-endpoint",
				"Period": "1h",
				"Limit": 120
			},

So that by default all my endpoints except for `my-non-authenticated-endpoint` would have the first rule, and `my-non-authenticated-endpoint` would have my second rule, but it doesnt seem to work that way? or do I have bad rules? I'm going off of IpRateLimiting with Redis, if it makes a difference.

**Comment by dupuis2387** [comment]
Sorry, i was being dense. I got what I needed by using 

`app.UseWhen(x => x.User.Identity.IsAuthenticated, builder => builder.UseClientRateLimiting());` 
`app.UseWhen(x => !x.User.Identity.IsAuthenticated, builder => app.UseIpRateLimiting());`

and configuring both `ClientRateLimiting` and `IpRateLimiting` settings in my appSettings.json file

**Comment by dupuis2387** [comment]
So, I kinda might have found an issue, or I'm not sure if I'm using it properly?
But, with 

`app.UseWhen(x => x.User.Identity.IsAuthenticated, builder => builder.UseClientRateLimiting());`
`app.UseWhen(x => !x.User.Identity.IsAuthenticated, builder => app.UseIpRateLimiting());`

It seems that both the IP rate limiter and the Client limiter Both run: first the client, then ip.
I get the Rate Limiting Headers from the Client rate limiter, and after debugging my way through the repo's source code, I saw that the Client one acts as expected. 

But, then the IP one also runs and I get blocked based off the rules of the IP rate limiter?

Is this to be expected?

**Comment by lakeman** [comment]
shouldn't that be `builder => builder.UseIpRateLimiting()` not `builder => app.UseIpRateLimiting()` ?

**Comment by dupuis2387** [comment]
> shouldn't that be `builder => builder.UseIpRateLimiting()` not `builder => app.UseIpRateLimiting()` ?

Ha! That was it. been staring at it so long i went blind. thanks for pointing that out!

**Comment by manisha201301** [comment]
@dupuis2387 d
Did you explored if there any way to override ``ResolveClientAsync(HttpContext httpContext)`` to use custom-client-id or ip-address based on a if-else condition?
