### ISSUE TITLE
Suggestion: Sample code in docs should include necessary using statements/references

### ISSUE THREAD

**Issue by davidpeden3** [stefanprodan/AspNetCoreRateLimit#15]
We don't use `<TOptions>` in our code and your sample code (copied from the [wiki](https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware#setup)) would not compile without explicitly adding a reference to `Microsoft.Extensions.Options.ConfigurationExtensions` in `project.json`. Tracking down the package necessary to make the code compile without having a hint from a `using` statement or an actual `dependencies` section from a `project.json` made the adoption process a bit harder than it should have been. I later discovered your demo project (which obviously had all necessary references) after pulling the source but it was not immediately obvious (to me, anyway).

**Comment by ted-spence-avalara** [comment]
+1

Thank you very much for posting this issue.

I would also recommend that you should update the dependencies to include this option.  I was very puzzled why the sample code in the documentation didn't work for me until I found this issue.

**Comment by cristipufu** [comment]
No longer applies for `netcoreapp3.0`
