### ISSUE TITLE
Regex path example for endpoints

### ISSUE THREAD

**Issue by dscaravaggi** [stefanprodan/AspNetCoreRateLimit#151]
Hi,
I noticed taht regex are supported I wonder If I can use a rule like this one

`\/api\?name=([^&]*)&auth=([^&]*)
`
`/api?name=s-12345xxx&auth=1234xxxx

where  group  \1 = 12345xxx and group  \2 = 1234xxxx

I would like to rate limit api for same name (e.g.: \1)
I cannot use only IP-Address because I'm facing a scenario with 3 offices behind 3 NAT router with about 50 persons for every office.

Ciao
Diego

**Comment by AprilHickson** [comment]
Hi,

I submitted a PR to add Regex to this library, it has been merged but not released yet.

Related issue: https://github.com/stefanprodan/AspNetCoreRateLimit/issues/136

Related PR: https://github.com/stefanprodan/AspNetCoreRateLimit/pull/135

I am still waiting on the release of this too.

**Comment by cristipufu** [comment]
https://github.com/stefanprodan/AspNetCoreRateLimit/releases/tag/3.2.0
