### ISSUE TITLE
Angular cannot get StatusCode 429 when requests are blocked

### ISSUE THREAD

**Issue by VictorLlanir** [stefanprodan/AspNetCoreRateLimit#156]
I have an WEB.API in .NET Core that need to limit requests. My front-end is developed in Angular, but it do not receive the 429 Status Code.

I created new projects to test, but the result is the same.
Below is the code of the Controller.

`
namespace WebApplication1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }

        [HttpPost]
        public IActionResult Post([FromBody] WeatherInput input)
        {
            Summaries.Append(input.Weather);
            return Ok();
        }
    }
    public class WeatherInput
    {
        public string Weather { get; set; }
    }
}
`

And below is the code in Angular that make the requests
`  get() {
    this.httpClient.get('https://localhost:44343/weatherforecast').subscribe(
      (result) => console.log(result),
      (error) => console.log(error)
    );
  }
  post() {
    const body = { weather: 'InputWeather' };
    this.httpClient
      .post('https://localhost:44343/weatherforecast', body)
      .subscribe(
        (result) => console.log(result),
        (error) => console.log(error)
      );
  }`

The two requests return me an StatusCode 0, like in the print below:
![image](https://user-images.githubusercontent.com/28709418/98544716-26a71680-2273-11eb-8267-a1cbd9a7003c.png)

But if I go to the Network tab, the chrome browser receives the 429, like below:
![image](https://user-images.githubusercontent.com/28709418/98544847-59e9a580-2273-11eb-8967-ae9bbbb08761.png)

And in Postman, for GET or POST, i receive the 429:
![image](https://user-images.githubusercontent.com/28709418/98544991-8ac9da80-2273-11eb-8232-24526b69389b.png)

![image](https://user-images.githubusercontent.com/28709418/98545009-91f0e880-2273-11eb-934e-96628c72314e.png)

Any of you have something like that? Is there a bug in Angular when receiving the answer of the AspNetCoreRateLimit?

**Comment by cristipufu** [comment]
You need to enable the CORS middleware [1] before the AspNetCoreRateLimit middleware [2].

[1] https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1
[2] https://stackoverflow.com/questions/52166778/angular-6-429-response-handling

**Comment by VictorLlanir** [comment]
Thank you! That solved the problem.

**Comment by JohnWeisz** [comment]
I also ran into this and a quick search landed me on this issue, which solved the problem, thank you!

Thinking about it a little more, the explanation for this behavior is rather obvious, however, I'm wondering if it should be added to the docs as a heads up in the config section.
