### ISSUE TITLE
Add support for Async Resolve Client

### ISSUE THREAD

**Issue by junderhill** [stefanprodan/AspNetCoreRateLimit#167]
Our given use case requires that when resolving a client we retrieve values from our persistent datastore. Given this call is asynchronous within our implementation of `IClientResolveContributor` we were required to await the result of an async call. 

As the current `IClientResolveContributor` only support synchronous operations this resulted in blocking the current thread which had a severe impact on the scalability and performance of our API.

Updating `IClientResolveContributor` to support an async `ResolveClient` would prevent this issue.

**Comment by junderhill** [comment]
I am working on the solution for this and will submit a pull request shortly.

**Comment by cristipufu** [comment]
Fixed
