### ISSUE TITLE
Dependency on IHttpContextAccessor is unnecessary.

### ISSUE THREAD

**Issue by mytrout** [stefanprodan/AspNetCoreRateLimit#174]
Because the IClientResolveContributor and IIpResolveContributor are both called in a method RateLimitMiddleware<TProcessor>.ResolveIdentityAsync(HttpContext httpContext) that has access to the current HttpContext, the need can be fulfilled by passing it as a parameter to the IClientResolveContributor.ResolveClientAsync() and IIpResolveContributor.ResolveIp() methods.

This approach also prevents any potential performance or usage mistakes of using IHttpContextAccessor or the caching of HttpContext that may find its way into the code base in later iterations. Since HttpContext will never be used in any other capacity in ClientHeaderResolveContributor or IpConnectionResolveContributor (or subsequent implementations), this implementation limits the misuse of HttpContext.

I have a local branch that demonstrates the change but am not authorized to push to this repo.

**Comment by cristipufu** [comment]
Hi @mytrout, thanks for your interest in this library. 

If you want to contribute, you need to fork the repository, make the changes on the fork and open a new pull request here.

**Comment by mytrout** [comment]
Pull Request submitted -> https://github.com/stefanprodan/AspNetCoreRateLimit/pull/175

**Comment by cristipufu** [comment]
Looking over the code, I identified a bug and fixed it, can you please resolve the conflicts?

**Comment by cristipufu** [comment]
Fixed by #175
