### ISSUE TITLE
Can't have a zero rate limit

### ISSUE THREAD

**Issue by icehowler** [stefanprodan/AspNetCoreRateLimit#18]
It seems I can't block an api call using 0 rate limit. You check if number is greater than 0 in your code. It would be useful to have some API that can be called only from localhost, like some jobs triggered by linux cron scheduler.

**Comment by matthew5025** [comment]
0 would be used to detonate no rate limiting, very much like most other similar application.

Only allowing API calls from localhost could be easily done with a simple if statement, and would probably not belong in this project.

**Comment by stefanprodan** [comment]
Blocking everything except localhost is a job for the firewall. If you want to allow API clients that you control, than use the client ID rate limiter. You can easy add the `X-ClientId` header to curl or whatever you are using to call your API from cron jobs.
