### ISSUE TITLE
[Question] Are there any plans for a new release?

### ISSUE THREAD

**Issue by junderhill** [stefanprodan/AspNetCoreRateLimit#186]
Hi,

Just wondering if you are planning a new release any time soon or if there is a set schedule for releases?

We're keen to use the official AspNetCoreRateLimit package as opposed the forked version we're currently using.

Many thanks
Jason

**Comment by cristipufu** [comment]
Published a new package version https://www.nuget.org/packages/AspNetCoreRateLimit/4.0.0
