### ISSUE TITLE
HttpContextAccessor still required.

### ISSUE THREAD

**Issue by xXBuilderBXx** [stefanprodan/AspNetCoreRateLimit#193]
With the latest update #175 and the demo project files HttpContextAccessor is still required and throws an error on startup.

![image](https://user-images.githubusercontent.com/17956143/108532972-5b922300-72d0-11eb-830d-04940b5c34f4.png)

**Comment by mytrout** [comment]
Please provide a code sample demonstrating this error and I will be glad to review it.

**Comment by mytrout** [comment]
@xXBuilderBXx : double-checked the Demo code after downloading Commit 5b21509a and everything works fine.  Could you check to make sure you have the latest commits from this project?

**Comment by sparksterz** [comment]
@xXBuilderBXx probably too late but this hasn't been built yet. I just ran into a similar issue while checking the `master` branch to implement my own resolver. 3.2.2 still requires the IHttpContextAccessor. The next library update presumably won't.

**Comment by simkin2004** [comment]
@cristipufu : Any idea when the code around my breaking change will be compiled and published?  The documentation that is currently in master doesn't match the latest published version 3.2.2.

**Comment by cristipufu** [comment]
Published a new version https://www.nuget.org/packages/AspNetCoreRateLimit/4.0.0
