### ISSUE TITLE
EndpointWhitelist wildcard does not work

### ISSUE THREAD

**Issue by st2forget** [stefanprodan/AspNetCoreRateLimit#21]
Here is my configuration

```
"IpRateLimiting": {
    "EnableEndpointRateLimiting": true,
    "StackBlockedRequests": false,
    "RealIpHeader": "X-Real-IP",
    "ClientIdHeader": "X-ClientId",
    "HttpStatusCode": 429,
    "IpWhitelist": [], // "127.0.0.1", "::1/10", "192.168.0.0/24"
    "EndpointWhitelist": [
      "get:*"
    ], //
    "ClientWhitelist": [ ],
    "GeneralRules": [
      {
        "Endpoint": "*",
        "Period": "1s",
        "Limit": 1
      },
      {
        "Endpoint": "*",
        "Period": "15m",
        "Limit": 100
      },
      {
        "Endpoint": "*",
        "Period": "12h",
        "Limit": 1000
      },
      {
        "Endpoint": "*",
        "Period": "7d",
        "Limit": 10000
      }
    ]
  }
```

Performing a GET request to /api/photos/{id} 2 times within 1s still give me response "429: API calls quota exceeded! maximum admitted 1 per 1s."

The EndpointWhitelist has [ "get:*" ] as I want all GET request should be allowed. Even if I set it to "get:/api/photo/*" still give same response (429)

**Comment by stefanprodan** [comment]
Hi

`get:*` is not a valid rule definition, can you please try `get:/api/photo`

**Comment by st2forget** [comment]
Thanks, I will give it a try

**Comment by st2forget** [comment]
You are right, it should be get:/api instead of get:/api/*. Many thanks for your support.
