### ISSUE TITLE
Service resolution error after upgrading to 4.0.0

### ISSUE THREAD

**Issue by wwarby** [stefanprodan/AspNetCoreRateLimit#216]
I have a project which is working fine on v3.2.2. After upgrading to 4.0.0 I had to make a couple of minor changes to my custom configuration class that derives from `RateLimitConfiguration` and add a `ResolveClientAsync` method to my `IClientResolveContributor` implementation in order to get the project to compile, but now I'm getting this error at startup:
```System.InvalidOperationException: Unable to resolve service for type 'AspNetCoreRateLimit.IProcessingStrategy' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.```

I'm struggling to trace the source of the problem - the service it's failing to activate seems to be internal to the library itself which shouldn't be my responsibility to register with the IoC container, and I can't see anything wrong with what I've done:

```
public class AppRateLimitConfiguration : RateLimitConfiguration {

	private readonly Func<ICurrentUserContext> _currentUser;

	public AppRateLimitConfiguration(
		IOptions<IpRateLimitOptions> ipOptions,
		IOptions<ClientRateLimitOptions> clientOptions,
		Func<ICurrentUserContext> currentUser
	) : base(ipOptions, clientOptions) {
		_currentUser = currentUser;
	}

	public override void RegisterResolvers() {
		base.RegisterResolvers();
		ClientResolvers.Add(new CurrentUserClientResolveContributor(_currentUser));
	}

}
```

```
public class CurrentUserClientResolveContributor : IClientResolveContributor {

	private readonly Func<ICurrentUserContext> _currentUser;

	public CurrentUserClientResolveContributor(Func<ICurrentUserContext> currentUser) {
		_currentUser = currentUser;
	}

	public string ResolveClient() {
		var user = _currentUser?.Invoke();
		if (user == null) { return string.Empty; }
		return user.IsMachineToMachine ? user.MachineToMachineApplicationId : user.Subject;
	}

	public Task<string> ResolveClientAsync(HttpContext httpContext) => Task.FromResult(ResolveClient());
}
```

**Comment by cristipufu** [comment]
You have to inject the [processing strategy](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/StartupExtensions.cs), eg:
```C#
services.AddSingleton<IProcessingStrategy, AsyncKeyLockProcessingStrategy>();
// services.AddSingleton<IProcessingStrategy, RedisProcessingStrategy>();
```

**Comment by wwarby** [comment]
Ah brilliant, that worked a treat - thanks

**Comment by lukeskinner** [comment]
Small suggestion, could the above comment about injecting the processing strategy be added into the release notes? It's not a breaking change but we did have to scan through the code and the PRs/issues to find the solution in here. 

The PR mostly covered about redis which I know we wanted the original processing strategy instead.
