### ISSUE TITLE
hello，How to set QuotaExceededResponse charset ？

### ISSUE THREAD

**Issue by wphubs** [stefanprodan/AspNetCoreRateLimit#219]
chinese message,

```
"QuotaExceededResponse": {
      "Content": "{{\"Result\":false,\"Msg\":\"访问过于频繁，请稍后重试\",\"Data\":null}}",
      "ContentType": "application/json;",
      "StatusCode": 200
},
```

![image](https://user-images.githubusercontent.com/50433222/121797194-495a3d00-cc51-11eb-9750-b662d0cb6d25.png)
![image](https://user-images.githubusercontent.com/50433222/121797211-61ca5780-cc51-11eb-98a2-01156fc2cbd3.png)

**Comment by cristipufu** [comment]
Works just fine, maybe the problem is the swagger page
![charset](https://user-images.githubusercontent.com/3955285/121900525-2f425c80-cd2e-11eb-8f98-6c1332b55b6a.JPG)
 rendering

**Comment by Leo0216** [comment]
其实问题在于你的appsettings.json文件使用的编码不正确，改为UTF-8即可。
