### ISSUE TITLE
ClientRateLimiting: Unable to limit requests per user, currently limits all the requests from different users/clients

### ISSUE THREAD

**Issue by dasadhanala** [stefanprodan/AspNetCoreRateLimit#223]
This is how I've setup my config: 

"ClientRateLimitingSettings": {
    "EnableEndpointRateLimiting": true,
    "StackBlockedRequests": false,
    "HttpStatusCode": 429,
    "GeneralRules": [
      {
        "Endpoint": "*:/api/*",
        "Period": "2s",
        "Limit": 1
      }
    ]
  }
  
I am trying to limit 1 request for every 2seconds per user. Currently, when two users hit the same endpoint at the exact same time. It limits one of the requests, by returning a 429. But I'm trying to apply this rule per user. 
  
What could I be missing here? 
  
Any help is appreciated. Thanks in advance!

**Comment by TheNillesen** [comment]
did you fix this since you closed the issue? i need help for exactly this problem

**Comment by Coke21** [comment]
I'm having the same issue. Could you show us your custom client resolver? @dasadhanala
