### ISSUE TITLE
Rate limiting counters for post endpoint

### ISSUE THREAD

**Issue by szymonpiekny** [stefanprodan/AspNetCoreRateLimit#224]
Hello,
I would report issue, I have configured rate limit for endpoint: 
"Endpoint": "post:/api/clients"
It works fine for endpoint: _https://localhost:5001/api/clients_
but when I send request to the same endpont with '/' at the end: _https://localhost:5001/api/clients**/**_ the rate limit is not working, I don't get headers in response related to rate limit eg. X-Rate-Limit-Limit, X-Rate-Limit-Remaining or X-Rate-Limit-Reset.
It should be stored under one counter, but it doesn't work now.
Could you look at this problem?
Thanks.

**Comment by szymonpiekny** [comment]
Hello,
It doesn't work now for GET endpoint, I have configured rate limit for:
"Endpoint": "**get**:/api/clients",
but I don't get headers in response related to rate limit eg. X-Rate-Limit-Limit, X-Rate-Limit-Remaining or X-Rate-Limit-Reset.

I tried to configure it as below:
"Endpoint": "**get**:/api/clients/*",
but rate limit counts separately for every parameter, if i call the same endpoint with different parameter: 
/api/clients/1 it will count from 100
/api/clients/2 it will count from 100

**Comment by cristipufu** [comment]
`get:/api/clients/*` is used as the counter key - so all endpoints that match this wildcard will count toward the same limit.

If you want to specify a different behavior (https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/CounterKeyBuilders/EndpointCounterKeyBuilder.cs), you need to implement a custom counter and override the default implementation, eg:
```C#
public class CustomRateLimitConfiguration : RateLimitConfiguration
{
    public override ICounterKeyBuilder EndpointCounterKeyBuilder { get; } = new EndpointCounterKeyBuilder();
}
```

**Comment by szymonpiekny** [comment]
Ok, if I configured it as below:
{
        "Endpoint": "get:/api/clients",
        "Period": "5m",
        "Limit": 100
}
It should return:
call get:/api/clients/1 99
call get:/api/clients/2 98

In current version you will not get headers related to rate limit.

**Comment by cristipufu** [comment]
`get:/api/clients` is a completely different endpoint than `get:/api/clients/x`.

If you want to rate limit endpoints like `get:/api/clients/x` to count towards the same limit, you need to:
- Set the configuration as:
```json
{
   "Endpoint": "get:/api/clients/*",
   "Period": "5m",
   "Limit": 100
}
```
- Implement a custom configuration class:
```C#
public class CustomRateLimitConfiguration : RateLimitConfiguration
{
    public override ICounterKeyBuilder EndpointCounterKeyBuilder { get; } = new EndpointCounterKeyBuilder();
}
```
- Inject the new configuration:
```C#
services.AddSingleton<IRateLimitConfiguration, CustomRateLimitConfiguration>();
```
