### ISSUE TITLE
CreateWebHostBuilder

### ISSUE THREAD

**Issue by LiamBartolini** [stefanprodan/AspNetCoreRateLimit#231]
Hi, I'm trying to implement the library, only it gives me errors when I write "CreateWebHostBuilder".
Any solution?
![image](https://user-images.githubusercontent.com/65280914/124627251-af686780-de7f-11eb-83b1-22e681105066.png)

Thanks in advance!

**Comment by cristipufu** [comment]
https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/test/AspNetCoreRateLimit.Demo/Program.cs#L36

**Comment by LiamBartolini** [comment]
thx 🙏🏻
