### ISSUE TITLE
Resolve error

### ISSUE THREAD

**Issue by ltemimi** [stefanprodan/AspNetCoreRateLimit#240]
Unable to resolve service for type 'AspNetCoreRateLimit.IProcessingStrategy' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.

When I added 
```
services.AddSingleton<IProcessingStrategy, ProcessingStrategy>();
```
I now get

Cannot instantiate implementation type 'AspNetCoreRateLimit.ProcessingStrategy' for service type 'AspNetCoreRateLimit.IProcessingStrategy'.

my configuration is as per instructions

Please help
Laz

**Comment by cristipufu** [comment]
https://github.com/stefanprodan/AspNetCoreRateLimit/issues/216
https://github.com/stefanprodan/AspNetCoreRateLimit/issues/236

**Comment by ltemimi** [comment]
216 above solved my problem thanks
