### ISSUE TITLE
[Question] Is there any way to override GeneralRules at Runtime?

### ISSUE THREAD

**Issue by manisha201301** [stefanprodan/AspNetCoreRateLimit#242]
Is there any way to override ``GeneralRules`` of ``[Client/Ip]RateLimiting`` at Runtime?
I saw we can rate-limit on specific Client-Ids, I wanted to know if there is a way to do that for general rules too?

Thnaks,
Manisha

**Comment by TySabs** [comment]
As far as I know, you cannot set `GeneralRules` at runtime. I was able to work around this by setting a rule for 0.0.0.0/0 (all ips) at runtime.

**Comment by zhouhaoJOKER** [comment]
> As far as I know, you cannot set `GeneralRules` at runtime. I was able to work around this by setting a rule for 0.0.0.0/0 (all ips) at runtime using this https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware#update-rate-limits-at-runtime.

this is a good idea!
