### ISSUE TITLE
Typo in ClientRateLimitPolicy example

### ISSUE THREAD

**Issue by joneal** [stefanprodan/AspNetCoreRateLimit#26]
In the code block that illustrates the ClientRateLimitPolicies, the first client rule has "ClientId", whereas the second rule has just "Client".  I believe the second rule should also have "ClientId" to match the class property.

"ClientRateLimitPolicies": {
    "ClientRules": [
      {
        "ClientId": "client-id-1",
        "Rules": [
          {
            "Endpoint": "*",
            "Period": "1s",
            "Limit": 10
          },
          {
            "Endpoint": "*",
            "Period": "15m",
            "Limit": 200
          }
        ]
      },
      {
        "Client": "client-id-2",
        "Rules": [
          {
            "Endpoint": "*",
            "Period": "1s",
            "Limit": 5
          },
          {
            "Endpoint": "*",
            "Period": "15m",
            "Limit": 150
          },
          {
            "Endpoint": "*",
            "Period": "12h",
            "Limit": 500
          }
        ]
      }
    ]
  }

**Comment by stefanprodan** [comment]
I've fixed it in the wiki https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/ClientRateLimitMiddleware

Thanks
