### ISSUE TITLE
How to use in Microsoft Azure with load balancing

### ISSUE THREAD

**Issue by ecoukraine** [stefanprodan/AspNetCoreRateLimit#27]
Hi Stefan,

thank you for the great feature! It's really cool! 
My app is hosted in Azure. I've read some description about distributed store but could not find any example. I've tried something like (instead of memory store) with no luck:
            services.AddSingleton<IIpPolicyStore, DistributedCacheIpPolicyStore>();
            services.AddSingleton<IRateLimitCounterStore, DistributedCacheRateLimitCounterStore>();

Would you be kind to share your idea how to use AspNetCoreRateLimit in Azure?

Thank you

**Comment by oatsoda** [comment]
Assuming you are using NetCore...

Add NuGet for:
> Microsoft.Extensions.Caching.Redis

In your Web App startup, add 

```
   services.AddDistributedRedisCache(options =>
   {
       options.Configuration = "your redis connection string"; // e.g. contoso5.redis.cache.windows.net,abortConnect=false,ssl=true,password=...
       options.InstanceName = "master";
   });'
```

This will ensure that the Redis implementation of `IDistributedCache` is registered into your DI container.

Then register AspNetCoreRateLimit as per the [wiki](https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware#setup):

```
   // Bind Settings and Policy
   services.Configure<IpRateLimitOptions>(Configuration.GetSection("IpRateLimiting"));
   services.Configure<IpRateLimitPolicies>(Configuration.GetSection("IpRateLimitPolicies"));

   // inject counter and rules stores
   services.AddSingleton<IIpPolicyStore, DistributedCacheIpPolicyStore>();
   services.AddSingleton<IRateLimitCounterStore, DistributedCacheRateLimitCounterStore>();
```

Don't forget to call `app.UseIpRateLimiting()` in your Web App startup too.

And don't forget to add all the [config ](https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/ClientRateLimitMiddleware#setup) into your `appSettings.json`

**Comment by MajidDehnamaki** [comment]
@oatsoda 
hi
i do this but show me this error:
`RedisConnectionException: No connection is available to service this operation: EVAL; SocketFailure on 192.168.1.69:6379/Subscription`

**Comment by oatsoda** [comment]
@MajidDehnamaki Perhaps your Redis connection string is wrong? Or some sort of Firewall/Connectivity issue between your App Service (I assume you are using a standard Azure App Service?) and your Redis.

It doesn't sound like an AspNetCoreRateLimit issue...

You might want to test out using the `IDistributedCache` [interface directly](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1) and once you get that working, then turn on the rate limiting.

**Comment by manisha201301** [comment]
Also, if you are using ``AspNetCoreRateLimit.Redis`` package with ``services.UseRedisRateLimiting()`` then you don't need to add the policy stores as they are added internally for you.
