### ISSUE TITLE
IpRateLimitProcessor requires IRateLimitCounterStore even though it is not used in code

### ISSUE THREAD

**Issue by aKzenT** [stefanprodan/AspNetCoreRateLimit#278]
IpRateLimitMiddleware requires a counter store, which is passed through IpRateLimitProcessor. However IpRateLimitProcessor doesn't actually use the counter store. When using RedisProcessingStrategy, there should be no need to register a counter store in the DI container.

**Comment by sizzle168** [comment]
I can confirm that.
