### ISSUE TITLE
Getting Error running script while connecting to Redis Cluster

### ISSUE THREAD

**Issue by sufyannisar** [stefanprodan/AspNetCoreRateLimit#289]
Hi,
We are getting error on all calls when using radis cluster with Rate Limiting. It works fine with Radis single installation but generates error when on cluster.

This is the error message:
_**ERR Error running script (call to f_994f13794c36f8e043af773c406a67b398d52fd6): @user_script:1: @user_script: 1: Lua script attempted to access a non local key in a cluster node**_ 

Here is the error stack:
```
   at AspNetCoreRateLimit.Redis.RedisProcessingStrategy.IncrementAsync(String counterId, TimeSpan interval, Func`1 RateIncrementer) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit.Redis\RedisProcessingStrategy.cs:line 38
   at AspNetCoreRateLimit.Redis.RedisProcessingStrategy.ProcessRequestAsync(ClientRequestIdentity requestIdentity, RateLimitRule rule, ICounterKeyBuilder counterKeyBuilder, RateLimitOptions rateLimitOptions, CancellationToken cancellationToken) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit.Redis\RedisProcessingStrategy.cs:line 28
   at AspNetCoreRateLimit.IpRateLimitProcessor.ProcessRequestAsync(ClientRequestIdentity requestIdentity, RateLimitRule rule, CancellationToken cancellationToken) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Core\IpRateLimitProcessor.cs:line 52
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 56
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by sufyannisar** [comment]
I have found this issue reported in StackExchange.Redis [issues#305](https://github.com/StackExchange/StackExchange.Redis/issues/305). 
Following those guidelines, I have updated RedisProcessingStrategy. I do not have access to push my changes and create a PR.

`using Microsoft.Extensions.Logging;
using StackExchange.Redis;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace AspNetCoreRateLimit.Redis
{
    public class RedisProcessingStrategy : ProcessingStrategy
    {
        private readonly IConnectionMultiplexer _connectionMultiplexer;
        private readonly IRateLimitConfiguration _config;
        private readonly ILogger<RedisProcessingStrategy> _logger;

        public RedisProcessingStrategy(IConnectionMultiplexer connectionMultiplexer, IRateLimitConfiguration config, ILogger<RedisProcessingStrategy> logger)
            : base(config)
        {
            _connectionMultiplexer = connectionMultiplexer ?? throw new ArgumentException("IConnectionMultiplexer was null. Ensure StackExchange.Redis was successfully registered");
            _config = config;
            _logger = logger;
        }

        //New Lua scripts for issue: https://github.com/StackExchange/StackExchange.Redis/issues/305
        private const string AtomicIncrement = "local count count = redis.call(\"INCRBYFLOAT\", KEYS[1], ARGV[1]) return count";

        private const string SetKeyExpiry = "redis.call(\"EXPIRE\",  KEYS[1], ARGV[1])";

        public override async Task<RateLimitCounter> ProcessRequestAsync(ClientRequestIdentity requestIdentity, RateLimitRule rule, ICounterKeyBuilder counterKeyBuilder, RateLimitOptions rateLimitOptions, CancellationToken cancellationToken = default)
        {
            var counterId = BuildCounterKey(requestIdentity, rule, counterKeyBuilder, rateLimitOptions);
            return await IncrementAsync(counterId, rule.PeriodTimespan.Value, _config.RateIncrementer);
        }

        public async Task<RateLimitCounter> IncrementAsync(string counterId, TimeSpan interval, Func<double> rateIncrementer = null)
        {
            var now = DateTime.UtcNow;
            var numberOfIntervals = now.Ticks / interval.Ticks;
            var intervalStart = new DateTime(numberOfIntervals * interval.Ticks, DateTimeKind.Utc);

            _logger.LogDebug("Calling Lua script. {counterId}, {timeout}, {delta}", counterId, interval.TotalSeconds, 1D);
            var db = _connectionMultiplexer.GetDatabase();
            var currentVal = rateIncrementer?.Invoke() ?? 1D;

            var count = await db.ScriptEvaluateAsync(AtomicIncrement, new RedisKey[] { counterId }, new RedisValue[] { currentVal });
            if (Math.Abs((double)count - currentVal) == 0)
            {
                await db.ScriptEvaluateAsync(SetKeyExpiry, new RedisKey[] { counterId }, new RedisValue[] { interval.TotalSeconds });
            }

            return new RateLimitCounter
            {
                Count = (double)count,
                Timestamp = intervalStart
            };
        }
    }
}`

**Comment by aKzenT** [comment]
I have added a pull request for this issue. StackExchangeRedis automatically adds parameters to the necessary KEYS collection when passing the parameter as a "RedisKey" object. See https://stackexchange.github.io/StackExchange.Redis/Scripting.html

There should be no need to split the script into two separate scripts as they both use the same key.

**Comment by sufyannisar** [comment]
I cannot find that Pull Request. Can you share your fix here?

**Comment by aKzenT** [comment]
@sufyannisar I'm sorry. I forgot to actually create the PR after forking.

**Comment by sufyannisar** [comment]
This resolved the issue, But I am getting another issue. I have 4 pods running in Kuernetics with Redis distributed rate limiting and have set up an IP limit for 3 requests per minute. When running on my machine, it works fine, but on Kuernetics, it serves 12 requests before saying the limit exceeded. Also, we are using Redis on a cluster with 3 nodes.
Here is my setup:

`public static IServiceCollection ConfigureRateLimiting(this IServiceCollection services, IConfiguration configuration)
{
	var redisConnectionString = configuration["ConnectionStrings:Redis"];

	var redisOptions = ConfigurationOptions.Parse(redisConnectionString);
	services.AddSingleton<IConnectionMultiplexer>(_ => ConnectionMultiplexer.Connect(redisOptions));

	services.Configure<IpRateLimitOptions>(configuration.GetSection("RateLimiting"));

	// inject counter and rules stores
	services.AddDistributedRateLimiting<CustomRedisProcessingStrategy>();

	services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

	// configuration (resolvers, counter key builders)
	services.AddSingleton<IRateLimitConfiguration, RateLimitConfiguration>();

	return services;
}

public static IApplicationBuilder AddRateLimiting(this IApplicationBuilder app)
{
	return app.UseIpRateLimiting();//.UseClientRateLimiting();
}`

Am I doing something wrong here?

**Comment by sufyannisar** [comment]
Found the issue. RealIpHeader in our case was different from X-Real-IP. It was X-Forwarded-For.

**Comment by pergardebrink** [comment]
Hi, we hit this issue as well as we are running a redis cluster. Is there a release planned for this fix? Is there anything we can do to help out?
