### ISSUE TITLE
Support Regex in the Path endpoints

### ISSUE THREAD

**Issue by AmirSasson** [stefanprodan/AspNetCoreRateLimit#3]
today it supports only "string.contains" in the "GetMatchingRules".
unfortunately i own a controller in which i need to protect a single action (GET) that gets a guid in the path.
for example:
1)HTTP GET : "**api/values/d3178e7b-acc0-41d1-a047-8453a6ca22c7**"
all other actions in this controller are meaningless to throttle.
for example:
2) HTTP GET : "**api/values/Seacrh/d3178e7b-acc0-41d1-a047-8453a6ca22c7**"

so i expect to have the ability to protect action 1, without harming action 2.
unfortunately if i protect "**get:/api/values/**"  so action 2 will be effected (as its path is contained in that path).

so the regex can be to protect only action 1.
^api/values/[A-Z0-9]{8}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{12}$

*****
**## on the contrary, this can be also achieved if the library would support "attributes" above the actions, to affect a specific action. (instead of config file)** which is even a better solution.

**Comment by stefanprodan** [comment]
Hello,

As a workaround, until I find some time to implement regex you can whitelist "get:/api/values/Search" and rate limit "get:/api/values/".

**Comment by ledouxpl** [comment]
I believe Controller and ActionMethods attributes are a must. This way, you have right in your controller the endpoint specific rules. This prevent mistakes when an api route is modified but the limit configuration is not updated to reflect the changes.

In my opinion, those attributes should be heavily inspired by the ASP.Net Core ResponseCache attributes.

The attributes should also support a way of applying the limit per action-method, per route (taking into account the route parameters), and even maybe by url (taking into account the query parameters).

**Comment by stefanprodan** [comment]
Would you hardcode IPs and client API keys in those attributes?

**Comment by ledouxpl** [comment]
Hmmm... Maybe use Profiles? Dressing again a parallel to ResponseCache,
something along the lines of the CachingProfileName property?

I honestly haven't given this enough thoughts to see all the potential
issues an attribute based approach could stir up, but I feel this warrants
being investigated a bit.

For context, my APIs make extensive use of route parameters. With the
current lack of regEx or intra string wildcards, I have a hard time making
use of the middleware. Adding support for those would be great. Adding
attributes on top of that would be even cooler.

**Comment by binsenpai** [comment]
Have IPs, and client API keys loaded from a configuration like before, attribute-based rules *as an option*, or just like before, load ratelimit rules from a file.

**Comment by zuckerthoben** [comment]
Like @ledouxpl I rely a lot on route parameters. I am currently implementing the middleware but just came across an issue, where I have to rate limit an endpoint that uses a route parameter. Not having the option of wildcards in endpoint paths is a blocking restriction.

**Comment by cristipufu** [comment]
check this out https://github.com/stefanprodan/AspNetCoreRateLimit/pull/63
