### ISSUE TITLE
How to ignore query string and/or parameters

### ISSUE THREAD

**Issue by andrzejpindor** [stefanprodan/AspNetCoreRateLimit#41]
Hi,
I have two actions in my API
List- GET /api/customers?query=
Details - GET /api/customers/{id}
which is executed like this

GET /api/customers?query=a
GET /api/customers?query=b

GET /api/customers/1
GET /api/customers/2

I want to specify rules separately for this two endpoints, ignoring parameters and/or querystrings.
In asp.net 4.5 version of your library I overrided "GetEndpoint" method on ThrottlingFilter and I achieved what I want. How can I get same behavior in asp.net core?
I tried a lot of combination of wildcards in config, like this:

`{
        "Endpoint": "GET:/api/customers/*",
        "Period": "15m",
        "Limit": 50
      },
{
        "Endpoint": "GET:/api/customers*",
        "Period": "15m",
        "Limit": 50
      },`

But I can't get what I need.
I'm using IpRateLimitProcessor which as I see use "IsMatch" extension method from WildcardMatcher - ClientRateLimitProcessor don't uses it.

@stefanprodan - maybe both implementations of middleware should allow to override part of codes that is resposible for controlling url match or you can explain is it possible to configure throttling out of the box as I described?

**Comment by cristipufu** [comment]
Check this out: https://github.com/stefanprodan/AspNetCoreRateLimit/pull/63
