### ISSUE TITLE
Limitation isn't applied on specific endpoint

### ISSUE THREAD

**Issue by Vladimarinescu** [stefanprodan/AspNetCoreRateLimit#46]
Hi Stefan,

This is my appsettings.json
`"IpRateLimiting": {
    "EnableEndpointRateLimiting": true,
    "StackBlockedRequests": true,
    "RealIpHeader": "X-Real-IP",
    "ClientIdHeader": "X-ClientId",
    "HttpStatusCode": 429,
    //"IpWhitelist": [ "127.0.0.1", "::1/10", "192.168.0.0/24" ],
    //"EndpointWhitelist": [ "get:/api/license", "*:/api/status" ],
    //"ClientWhitelist": [ "dev-id-1", "dev-id-2" ],
    "GeneralRules": [
      {
        "Endpoint": "*:api/account/ActivateUser",
        "Period": "20m",
        "Limit": 1
      }   
    ]
  }`

And this is the route that i'm calling from my angular spa
`http://localhost:59323/api/account/ActivateUser`

The limitation isn't applied. On the other side, if i'm using : `  "Endpoint": "*",` everything works O.K

Any idea? Thanks

**Comment by Vladimarinescu** [comment]
Also, if i use */account/ActivateUser works, why?

**Comment by Ueterbock** [comment]
I´ve got the exact same scenario and also tried several endpoint definitions for my route /api/test:
`
 {
        "Endpoint": "get:/api/test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "*:/api/test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "*:/api/Test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "get:/api/Test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "*api/Test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "*api/test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "*/Test",
        "Period": "1h",
        "Limit": 20
      },
      {
        "Endpoint": "*/test",
        "Period": "1h",
        "Limit": 20
      }
`

It will only work if the endpoint is defined with an asterisk.

**Comment by RaddadZ** [comment]
i think if your url is `http://localhost:59323/api/account/ActivateUser` then your endpoint should be 
```
{ 
   "Endpoint": "*:/api/account/ActivateUser", 
   "Period": "20m", 
   "Limit": 1 
}
```

**Comment by cristipufu** [comment]
The Wildcard match issues are fixed here: https://github.com/stefanprodan/AspNetCoreRateLimit/pull/63
