### ISSUE TITLE
Not working with .net core 2.2

### ISSUE THREAD

**Issue by flyinb** [stefanprodan/AspNetCoreRateLimit#56]
Not working with .net core 2.2

![image](https://user-images.githubusercontent.com/11261905/49889638-47ecf700-fdff-11e8-8b6e-2182a7296b7a.png)

![image](https://user-images.githubusercontent.com/11261905/49889595-2d1a8280-fdff-11e8-99e1-5ce50eaa2565.png)

**Comment by da1rren** [comment]
It works fine with .net core 2.2.  You can safely ignore that warning.
