### ISSUE TITLE
Parsing reverse proxy IP

### ISSUE THREAD

**Issue by Dissimilis** [stefanprodan/AspNetCoreRateLimit#6]
I think ReverseProxyIpParser.cs should take last item instead of first by default. Or at least it should be mentioned in docs / easy to override / investigated further.
Thing is that most reverse proxies (CloudFlare, Azure, etc) appends IP address is header already exists. So when you take first IP from list it is more likely to be spoofed. 
So IMHO Last() is safer default. And some Func<Request, IPAddress> would be even better.

**Comment by stefanprodan** [comment]
You can implement your own [IIpAddressParser](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Net/IIPAddressParser.cs) and inject that, it will override the default [ReversProxyIpParser](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Net/ReversProxyIpParser.cs).

You can do this in Startup.cs like this:

```cs
services.AddSingleton<IIpAddressParser, MyCoustomIpAddressParser>();
```
