### ISSUE TITLE
I'm really confused on the versions

### ISSUE THREAD

**Issue by RobThree** [stefanprodan/AspNetCoreRateLimit#61]
![untitled-1](https://user-images.githubusercontent.com/607888/52279464-ec9c3880-2959-11e9-96c4-bff79b8ba736.png)

I am really confused on the versions/branch/whatever and which I am supposed to use for a .Net Core 2.2 application.

Also, there are a lot of issues still unanswered in this project. Is it still being actively maintained or should I look for alternatives?

**Comment by cristipufu** [comment]
Some guys forked the code and published the library without changing the author. The "official" NuGet package should be the one with the 2.1.0 version (without the `Stackexchange.Redis` dependency)
