### ISSUE TITLE
Exception during startup after updating to 3.0.2

### ISSUE THREAD

**Issue by Veflow** [stefanprodan/AspNetCoreRateLimit#66]
Getting the following exception after updating the package to 3.0.2:

`System.InvalidOperationException: 'Unable to resolve service for type 'AspNetCoreRateLimit.IRateLimitConfiguration' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.'`

Fixed by adding the following line to my own container configuration:
`builder.RegisterType(typeof(RateLimitConfiguration)).As(typeof(IRateLimitConfiguration)).SingleInstance();`
(I'm using Autofac.)

**Comment by cristipufu** [comment]
[Version 3 Breaking Changes](https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/Version-3.0.0-Breaking-Changes)

Register two new services in Startup.cs:

```C#
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddSingleton<IRateLimitConfiguration, RateLimitConfiguration>();
```

**Comment by Veflow** [comment]
Thanks for the clarification. Did not initially find the Breaking Changes page. Would be handy if it's linked under the releases tab.

Anyways, it's clear for me now. Thanks again.

**Comment by colgreen** [comment]
I think the two new service registrations should be added to the wiki:

   https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware

**Comment by lawrence-laz** [comment]
Any particular reason this library does not provide an `IServiceCollection` extension method for simpler registration?
