### ISSUE TITLE
Autofac issue on 3.0.2

### ISSUE THREAD

**Issue by JonnyXDA** [stefanprodan/AspNetCoreRateLimit#67]
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'AspNetCoreRateLimit.IClientPolicyStore' has not been registered. To avoid this exception, either register a component to provide the service, chec
k for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType) in C:\projects\autofac-extensions-dependencyinjection\src\Autofac.Extensions.DependencyInjection\AutofacServiceProvider.cs:
line 71
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

**Comment by cristipufu** [comment]
Hi @JonnyXDA, have you read the [documentation](https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/ClientRateLimitMiddleware#setup)?

You have to register the client policy store (in-memory/distributed cache store):

```C#
public void ConfigureServices(IServiceCollection services)
{
	// needed to load configuration from appsettings.json
	services.AddOptions();

	// needed to store rate limit counters and ip rules
	services.AddMemoryCache();

	//load general configuration from appsettings.json
	services.Configure<ClientRateLimitOptions>(Configuration.GetSection("ClientRateLimiting"));

	//load client rules from appsettings.json
	services.Configure<ClientRateLimitPolicies>(Configuration.GetSection("ClientRateLimitPolicies"));

	// inject counter and rules stores
	services.AddSingleton<IClientPolicyStore, MemoryCacheClientPolicyStore>();
	services.AddSingleton<IRateLimitCounterStore, MemoryCacheRateLimitCounterStore>();

	// Add framework services.
	services.AddMvc();

        // https://github.com/aspnet/Hosting/issues/793
        // the IHttpContextAccessor service is not registered by default.
        // the clientId/clientIp resolvers use it.
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

        // configuration (resolvers, counter key builders)
        services.AddSingleton<IRateLimitConfiguration, RateLimitConfiguration>();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	app.UseClientRateLimiting();

	app.UseMvc();
}
```

**Comment by cristipufu** [comment]
Reference: https://github.com/stefanprodan/AspNetCoreRateLimit/issues/66

**Comment by JonnyXDA** [comment]
I have read the documentation and have all the needed lines and still get the issue, hence why I opened this issue ticket

**Comment by cristipufu** [comment]
The error you are receiving is pretty straight forward (couldn't find that service in the container).

It seems that you are using `AutoFac` (instead of the default dependency injection container), so you probably need to replace those calls with something like:

```C#
// inject counter and rules stores
builder.RegisterType(typeof(MemoryCacheClientPolicyStore)).As(typeof(IClientPolicyStore)).SingleInstance();
builder.RegisterType(typeof(MemoryCacheRateLimitCounterStore)).As(typeof(IRateLimitCounterStore)).SingleInstance();

builder.RegisterType(typeof(HttpContextAccessor)).As(typeof(IHttpContextAccessor)).SingleInstance();
builder.RegisterType(typeof(RateLimitConfiguration)).As(typeof(IRateLimitConfiguration)).SingleInstance();
```

**Comment by JonnyXDA** [comment]
Thanks, it was this line that was missing:

services.AddSingleton<IClientPolicyStore, MemoryCacheClientPolicyStore>();

We were only using IP rate limiting, not Client rate limiting, so this was not included originally
