### ISSUE TITLE
Exception when seeding policy store with distributed SQL Server cache in 3.0.2

### ISSUE THREAD

**Issue by johansme** [stefanprodan/AspNetCoreRateLimit#68]
The `SeedAsync` method of the `DistributedCacheIpPolicyStore` and the `DistributedCacheClientPolicyStore` both call the `SetAsync` method of the `DistributedCacheRateLimitStore` with only the `id` and `entry` parameters set.
This means that the `IDistributedCache`'s `SetStringAsync` method is called with the `options` (third) parameter set to `null`.
However, when using a `DistributedSqlServerCache` as the `IDistributedCache`, this `null` argument is propagated to the `SetAsync` method, where it throws an `ArgumentNullException`. In other words, seeding the policy store can never succeed when the distributed cache is an SQL Server cache.

**Comment by cristipufu** [comment]
Hi @johansme, thanks for reporting this.

Indeed, it seems there's a `null` parameters check:
1. [RedisCache](https://github.com/aspnet/Extensions/blob/aabe8c34a62786c313e20125d70b36d3c5e72a75/src/Caching/StackExchangeRedis/src/RedisCache.cs)
2. [SqlServerCache](https://github.com/aspnet/Extensions/blob/aabe8c34a62786c313e20125d70b36d3c5e72a75/src/Caching/SqlServer/src/SqlServerCache.cs)
