### ISSUE TITLE
change logLevel

### ISSUE THREAD

**Issue by critot** [stefanprodan/AspNetCoreRateLimit#7]
Hello,
I'm trying to change logLevel of IpRateLimitMiddleware, for what I understood I have to inherit from IpRateLimitMiddleware and override LogBlockedRequest

this is what I've done, probably wrong because it doesn't work...

services.AddOptions();
services.AddMemoryCache();
services.Configure<IpRateLimitOptions>(Configuration.GetSection("IpRateLimiting"));
services.Configure<IpRateLimitPolicies>(Configuration.GetSection("IpRateLimitPolicies"));
services.AddSingleton<IIpPolicyStore, MemoryCacheIpPolicyStore>();
services.AddSingleton<IRateLimitCounterStore, MemoryCacheRateLimitCounterStore>();

services.AddSingleton<IpRateLimitMiddleware, IpRateLimitMiddlewareCustom>();

....
    public class IpRateLimitMiddlewareCustom: IpRateLimitMiddleware
    {
        private ILogger<IpRateLimitMiddleware> _logger;

        public IpRateLimitMiddlewareCustom(RequestDelegate next, IOptions<IpRateLimitOptions> options, IRateLimitCounterStore counterStore, IIpPolicyStore policyStore, ILogger<IpRateLimitMiddleware> logger, IIpAddressParser ipParser = null) : base(next, options, counterStore, policyStore, logger, ipParser)
        {
            _logger = logger;
        
        }

        public override void LogBlockedRequest(HttpContext httpContext, ClientRequestIdentity identity, RateLimitCounter counter, RateLimitRule rule)
        {
            _logger.LogWarning($"Request {identity.HttpVerb}:{identity.Path} from IP {identity.ClientIp} has been blocked, quota {rule.Limit}/{rule.Period} exceeded by {counter.TotalRequests}. Blocked by rule {rule.Endpoint}, TraceIdentifier {httpContext.TraceIdentifier}.");
        }

    }

this is the output

AspNetCoreRateLimit.IpRateLimitMiddleware:Information: Request options:.........

thank you!

**Comment by stefanprodan** [comment]
You could try this:

```
    public static class MyMiddlewareExtensions
    {
        public static IApplicationBuilder UseCustomIpRateLimiting(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<IpRateLimitMiddlewareCustom>();
        }       
    }
```

And in Startup.Configure use your implementation:

```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            ...
            app.UseCustomIpRateLimiting();
            ...
        }
```

Also remove the singleton:

```
services.AddSingleton<IpRateLimitMiddleware, IpRateLimitMiddlewareCustom>();
```

**Comment by critot** [comment]
yes! it works, thank you!
