### ISSUE TITLE
Change log and release for v3+

### ISSUE THREAD

**Issue by beefo** [stefanprodan/AspNetCoreRateLimit#71]
Version 3.0.2, 3.0.1 and 3.0.0 were released to nuget with no change log and/or release in git releases. Could it be added? Is this a breaking change as major version increase suggests?

**Comment by fschlaef** [comment]
More info here : 

https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/Version-3.0.0-Breaking-Changes

https://github.com/stefanprodan/AspNetCoreRateLimit/pull/63

**Comment by cristipufu** [comment]
https://github.com/stefanprodan/AspNetCoreRateLimit/releases/tag/3.0.3
