### ISSUE TITLE
Throttling only on anonymous endpoints

### ISSUE THREAD

**Issue by jasonycw** [stefanprodan/AspNetCoreRateLimit#75]
We are trying to add throttling for our anonymous endpoints only, but couldn't figure out how to write the rule for that.

Not sure if it is the same as https://github.com/stefanprodan/AspNetCoreRateLimit/issues/37

It there is support for attribute, it will be great too. https://github.com/stefanprodan/AspNetCoreRateLimit/issues/49

**Comment by JakubSurfer** [comment]
you can use this in asp net core app :

`app.UseWhen(x => !x.User.Identity.IsAuthenticated, builder => builder.UseIpRateLimiting());`

**Comment by jasonycw** [comment]
@JakubSurfer This works great! Thanks.

Note to myself: put that after `.UseAuthentication()`
