### ISSUE TITLE
ClientIpHeader is not used under IpRateLimitOptions

### ISSUE THREAD

**Issue by jasonycw** [stefanprodan/AspNetCoreRateLimit#77]
According to https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware

For `IpRateLimitOptions`

> The `ClientIdHeader` is used to extract the client id for white listing. If a client id is present in this header and matches a value specified in ClientWhitelist then no rate limits are applied.

However in `RateLimitCongiguration`
https://github.com/stefanprodan/AspNetCoreRateLimit/blob/f56fecfd52f213b81ba9275f78e09b687df265ed/src/AspNetCoreRateLimit/Middleware/RateLimitConfiguration.cs#L33-L47

Only the `ClientRateLimitOptions.ClientIdHeader` is used for `ClientResolver`.
So when I use `IpRateLimitOptions`, the `ClientIdHeader` is not used and the `requestIdentity.ClientId` under `RateLimitorProcessors` are not pointing to the correct header value.

**Comment by cristipufu** [comment]
Fixed by https://github.com/stefanprodan/AspNetCoreRateLimit/commit/001b46414c52cd859c6118aaa54e799f64dfc9ee
