### ISSUE TITLE
Option not to send response headers

### ISSUE THREAD

**Issue by gallivantor** [stefanprodan/AspNetCoreRateLimit#8]
Great library!

I'm using this middleware to protect my API from abuse -- so I wouldn't expect any reasonable user to hit the limits that I've set. Therefore, if an abusive user does hit the limits then I don't want them to know my policy settings so that they can just wait and start spamming the API again after the timeout.

Therefore, I'd like an option to disable the sending of the Retry-After header and the X-Rate-Limit-xxx headers so that the client is not informed about when they can start abusing the API again.

**Comment by stefanprodan** [comment]
You can now set `DisableRateLimitHeaders` to `true` in  appsettings, this option is available in v1.0.4

**Comment by gallivantor** [comment]
That's great, thanks!
