### ISSUE TITLE
VS 2017 Install-Package WebApiThrottle -Version 1.5.4 Error

### ISSUE THREAD

**Issue by DreamITSoftware** [stefanprodan/AspNetCoreRateLimit#84]
Getting the following error when trying to install the package in VS 2017.

Install-Package WebApiThrottle -Version 1.5.4
Restoring packages for C:\Users\Dan\source\repos\WebApplication23\WebApplication23\WebApplication23.csproj...
Installing NuGet package WebApiThrottle 1.5.4.
Committing restore...
Writing lock file to disk. Path: C:\Users\Dan\source\repos\WebApplication23\WebApplication23\obj\project.assets.json
Restore completed in 909.91 ms for C:\Users\Dan\source\repos\WebApplication23\WebApplication23\WebApplication23.csproj.
Successfully installed 'Microsoft.AspNet.WebApi.Core 5.2.3' to WebApplication23
Successfully installed 'Microsoft.Owin 3.0.1' to WebApplication23
Successfully installed 'Owin 1.0.0' to WebApplication23
Successfully installed 'WebApiThrottle 1.5.4' to WebApplication23
Executing nuget actions took 1.46 sec
Time Elapsed: 00:00:02.5105531
PM> unInstall-Package WebApiThrottle -Version 1.5.4
Restoring packages for C:\Users\Dan\source\repos\WebApplication23\WebApplication23\WebApplication23.csproj...
Committing restore...
Writing lock file to disk. Path: C:\Users\Dan\source\repos\WebApplication23\WebApplication23\obj\project.assets.json
Restore completed in 840.69 ms for C:\Users\Dan\source\repos\WebApplication23\WebApplication23\WebApplication23.csproj.
Successfully uninstalled 'Microsoft.AspNet.WebApi.Core 5.2.3' from WebApplication23
Successfully uninstalled 'Microsoft.Owin 3.0.1' from WebApplication23
Successfully uninstalled 'Owin 1.0.0' from WebApplication23
Successfully uninstalled 'WebApiThrottle 1.5.4' from WebApplication23
Executing nuget actions took 375.5 ms
Time Elapsed: 00:00:01.6222598
PM> Install-Package AspNetCoreRateLimit -Version 3.0.5
Restoring packages for E:\Dev\swaytrader.io\SwayTrader\Raptor\Core\Licensing\RaptorLicensingService\RaptorLicensingService\RaptorLicensingService.csproj...
Install-Package : NU1107: Version conflict detected for Microsoft.Extensions.Logging. 
Install/reference Microsoft.Extensions.Logging 2.2.0 directly to project RaptorLicensingService to 
resolve this issue. 
 RaptorLicensingService -> AspNetCoreRateLimit 3.0.5 -> Microsoft.Extensions.Logging (>= 2.2.0) 
 RaptorLicensingService -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Logging (>= 2.1.1 
&& < 2.2.0).At line:1 char:1
+ Install-Package AspNetCoreRateLimit -Version 3.0.5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets 
   .InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 
'RaptorLicensingService'.At line:1 char:1
+ Install-Package AspNetCoreRateLimit -Version 3.0.5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets 
   .InstallPackageCommand

**Comment by cristipufu** [comment]
You need to update your AspNetCore version:
> RaptorLicensingService -> AspNetCoreRateLimit 3.0.5 -> Microsoft.Extensions.Logging (>= 2.2.0)
RaptorLicensingService -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Logging (>= 2.1.1
&& < 2.2.0)
