### ISSUE TITLE
Read the IpRateLimitPolicies from a SQL Database

### ISSUE THREAD

**Issue by SergentGarcia** [stefanprodan/AspNetCoreRateLimit#87]
Hi,
Is it possible to read the IpRateLimitPolicies from a SQL Database instead of reading them from the appSettings.json file ?
Thanks a lot,

**Comment by randaarchitect** [comment]
You can accomplish that with a Custom ConfigurationProvider at Startup.

**Comment by SergentGarcia** [comment]
I tried like this :

services.Configure<IpRateLimitPolicies>(option => option.IpRules = RateLimitingTools.GetIpRateLimitPoliciesFromDatabase());

GetIpRateLimitPoliciesFromDatabase() will access the database and fill in the IpRateLimitPolicies.
Is that the solution you were thinking of?

Thanks

**Comment by randaarchitect** [comment]
I was thinking more along the lines of:

public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration(AddDbConfiguration)
        .UseStartup<Startup>();
		
...
		
private static void AddDbConfiguration(WebHostBuilderContext context, IConfigurationBuilder builder)
{
    var configuration = builder.Build();
    var connectionString = configuration.GetConnectionString("RateLimitDatabase");
    builder.AddRateLimitDbProvider(options => options.UseSqlServer(connectionString));
}

Check out this article: https://medium.com/@dneimke/custom-configuration-in-net-core-2-193ff6f02046

**Comment by SergentGarcia** [comment]
Thanks a lot, I'll try this right now!

**Comment by cristipufu** [comment]
One can implement his own `IClientPolicyStore` or `IIpPolicyStore` - by inheriting the `MemoryCacheClientPolicyStore` or the `DistributedCacheClientPolicyStore` and overriding the `SeedAsync()` method:

```C#
public class DatabaseCacheClientPolicyStore : MemoryCacheClientPolicyStore
{
    public DatabaseCacheClientPolicyStore() : base(cache, options, policies) {}

    public new async Task SeedAsync()
    {
        if (_options != null)
        {
            var policies = await _databasePoliciesRepository.GetClientPolicies();

            foreach (var rule in policies)
            {
                await SetAsync($"{_options.ClientPolicyPrefix}_{rule.ClientId}", new ClientRateLimitPolicy { ClientId = rule.ClientId, Rules = rule.Rules });
            }
        }
    }
}
```
