### ISSUE TITLE
Is it possible to override a rate on a specific endpoint?

### ISSUE THREAD

**Issue by gbrunton** [stefanprodan/AspNetCoreRateLimit#88]
I have the following GeneralRule

```
 {
        "Endpoint": "*",
        "Period": "1m",
        "Limit": 2
   }
```

Can I add another GeneralRule (or something) that overrides this rate limit. I want to do something like the following

```
 {
        "Endpoint": "*",
        "Period": "1s",
        "Limit": 2
   },
 {
        "Endpoint": "*:/validate",
        "Period": "1s",
        "Limit": 10
   }
```
By this I mean that all endpoints except for the /validate endpoint should only allow 2 calls per second. The /validate endpoint should allow 10 calls per second.

I can't seem to get this to work.

**Comment by garethbudden** [comment]
I also need to do this - was there a solution?

**Comment by mikerodey** [comment]
Endpoint needs the trailing forward slash

e.g.
 {
        "Endpoint": "*:/validate/",
        "Period": "1s",
        "Limit": 10
   }

**Comment by cristipufu** [comment]
You also need to enable it (else it will only search for `rules.Where(r => r.Endpoint == "*")`):
```json
"IpRateLimiting": {
    "EnableEndpointRateLimiting": true,
```
