### ISSUE TITLE
Mix Global and Endpoint Rules

### ISSUE THREAD

**Issue by kspearrin** [stefanprodan/AspNetCoreRateLimit#9]
Is it possible to mix a global rule with specific endpoint rules? For example I want to limit all endpoints globally to 1000 calls every 1 hour, but I also want to limit a specific endpoint with a more strict rule, like 1 per second. The documentation seems to indicate this is global or not with the `EnableEndpointRateLimiting` flag.

**Comment by stefanprodan** [comment]
Here is an example:

```json
    "GeneralRules": [
      {
        "Endpoint": "*",
        "Period": "1h",
        "Limit": 1000
      },
      {
        "Endpoint": "*:/api/values",
        "Period": "1s",
        "Limit": 1
      }
    ]
```

This sets 1000 calls per hour to all endpoints and a limit of 1 call per second for the /api/values endpoints targeting all HTTP verbs.

**Comment by kspearrin** [comment]
Do I set `EnableEndpointRateLimiting` to true or false when doing this?

**Comment by stefanprodan** [comment]
You have to set `EnableEndpointRateLimiting=true` for the endpoints limits to apply.

**Comment by kspearrin** [comment]
Got it. Thanks.
