### ISSUE TITLE
Default rate limit for individual client

### ISSUE THREAD

**Issue by nivas07** [stefanprodan/AspNetCoreRateLimit#92]
Hi, I'm using client rate limiting.
I'm facing below behavior. 
 General settings rate limits are applied globally, not per user. If the general settings allow 1000 requests per minute, then this 1000 is shared by all users, it is not 1000 rpm per user. 
I need to specify settings that allows 1000 rpm per user. But I cannot create individual client rules for all client ids due to huge number of client ids. 
Please let me know how to achieve this. 
Is there any wildcard for clientid in clientratelimit rules?

**Comment by cristipufu** [comment]
Well, if you use the `ClientRateLimitMiddleware`, you have to have a header or something that uniquely identifies the user:
```json
"ClientRateLimiting": {
    "EnableEndpointRateLimiting": true,
    "ClientIdHeader": "X-Client-Id",
}
```
You could also use the `IpRateLimitMiddleware`.

**Comment by nivas07** [comment]
I'm using a customratelimitmiddleware class inherited from clientratelimitmiddleware. In SetIdentity method I'm using the 'sub' claim retrieved from jwt token and set it as ClientId of ClientRequestIdentity. Do I need to modify anything else here?

**Comment by cristipufu** [comment]
Well, it sounds like you are using the previous version (2.x.x) of the package. In the new version, one can implement custom resolvers: https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/Resolve-Contributors
