### ISSUE TITLE
Limitation isn't applied on specific endpoint

### ISSUE THREAD

**Issue by namnik** [stefanprodan/AspNetCoreRateLimit#96]
I read #46 
but I have the same problem!.

my appsetting

  "IpRateLimiting": {
    **"EnableEndpointRateLimiting": true,**
    "StackBlockedRequests": false,
    "RealIpHeader": "X-Real-IP",
    "ClientIdHeader": "X-ClientId",
    "HttpStatusCode": 429,
    "IpWhitelist": [], //"127.0.0.1", "::1/10", "192.168.0.0/24"
    "EndpointWhitelist": [ "get:/api/basis/product/parents" ],
    "ClientWhitelist": [], //"dev-id-1", "dev-id-2"
    "GeneralRules": [
      {
        ****"Endpoint": "*:/api/basis/personTypes",**
        "Period": "10s",
        "Limit": 4
      },
      {
        **"Endpoint": "'*'",**
        "Period": "10s",
        "Limit": 2
      }
    ]
  }
}

now, be apply aesterik endpoint limit(*)
but I want to apply  ****"Endpoint": "*:/api/basis/personTypes",**

how?!
tnx a lot

**Comment by hueifeng** [comment]
The Wildcard match issues are fixed here: #63
