### ISSUE TITLE
Is there a reason why you can't apply an IP whitelist using ClientRateLimiting

### ISSUE THREAD

**Issue by DomGarbett** [stefanprodan/AspNetCoreRateLimit#98]
Is it by design that you are unable to set an IP WhiteList whilst using the client rate limiting rules. 

Yet when using IP rate limiting rules you are able to set a client ID whitelist.

Has this been intentionally left out, or is this an issue that can be fixed via a PR ?

**Comment by gaborbuzasi** [comment]
I would be interested in this too. Is there a way you could whitelist certain IP addresses from rate limitation when using ClientId based rate limiting?

**Comment by cristipufu** [comment]
Fixed by https://github.com/stefanprodan/AspNetCoreRateLimit/commit/001b46414c52cd859c6118aaa54e799f64dfc9ee
